import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { FloatingNav } from "@/components/FloatingNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navItems = [
    { name: "Home", link: "#" },
    { name: "About", link: "#about" },
    /* { name: "Projects", link: "#projects" }, */
    /* { name: "Testimonials", link: "#testimonials" }, */
    { name: "Contact", link: "#contact" },
  ];

  return (
    <html lang="en" suppressHydrationWarning style={{ cursor: "none" }}>
      <body className={geistMono.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {/* <FloatingNav navItems={navItems} /> */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
